<script type="text/javascript">
jQuery.noConflict();
document.addEventListener('DOMContentLoaded', function(){ 
jQuery.getScript('https://ssl.geoplugin.net/javascript.gp?k=e41869f2d131d37c');
jQuery.getScript('https://www.google.com/jsapi');
if (typeof jQuery == 'undefined')   {
         document.write(unescape("%3Cscript src='//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js' type='text/javascript'%3E%3C/script%3E"));
    }
});
</script> 