<?php
/**
 * @category    Wyomind
 * @package     Wyomind_Elasticsearch
 * @version     4.5.0
 * @copyright   Copyright (c) 2017 Wyomind (https://wyomind.net)
 */
/**
 * @var $this Wyomind_Elasticsearch_Block_Catalogsearch_Autocomplete_Product
 */
$_product = $this->getEntity();
$_displayImage = $this->getDisplayImage();
if ($_displayImage == null) $_displayImage = 1;
$_imgSize = $this->getImageSize();
?>
<?php if ($_product): ?>
<li>
    <a href="<?php echo $this->escapeUrl($this->getProductUrl($_product)) ?>"
       title="<?php echo $this->escapeHtml($_product->getName()) ?>">
        <?php if ($_displayImage && $_src = $this->getImageSrc()): ?>
            <div class="image" style="min-height: <?php echo $_imgSize ?>px;">
                <img src="<?php echo $_src; ?>" width="<?php echo $_imgSize ?>" alt="<?php echo $this->escapeHtml($_product->getName()) ?>" />
            </div>
        <?php endif ?>
        <div class="info">
            <span class="name"><?php echo $this->escapeHtml($_product->getName()) ?></span>
            <span class="price"><?php echo $this->getPriceHtml($_product) ?></span>
        </div>
        <div class="clearer"><!-- --></div>
    </a>
</li>
<?php endif ?>