<?php
$optionid = Mage::helper("marketplace")->getProuctVendorid(Mage::getSingleton('admin/session')->getUser()->getUserId());
	$productCollection = Mage::getModel('catalog/product')->getCollection()->addAttributeToFilter('vendor_id',$optionid);
	$productIDs=$productCollection->getAllIds();
	  $current_user = Mage::getSingleton('admin/session')->getUser();
	$_roleId=$current_user->getRole()->getRoleId();

	$roleId=Mage::helper("marketplace")->getVendorRoleId();
?>
<?php $_order = $this->getOrder() ?>
<div class="grid np">
  <div class="hor-scroll">
    <table cellspacing="0" class="data order-tables">
        <col />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <thead>
            <tr class="headings">
                <th><?php echo $this->helper('sales')->__('Product') ?></th>
                <th><span class="nobr"><?php echo $this->helper('sales')->__('Item Status') ?></span></th>
                <th><span class="nobr"><?php echo $this->helper('sales')->__('Original Price') ?></span></th>
                <th><?php echo $this->helper('sales')->__('Price') ?></th>
                <th class="a-center"><?php echo $this->helper('sales')->__('Qty') ?></th>
                <th><?php echo $this->helper('sales')->__('Subtotal') ?></th>
                <th><span class="nobr"><?php echo $this->helper('sales')->__('Tax Amount') ?></span></th>
                <th><span class="nobr"><?php echo $this->helper('sales')->__('Tax Percent') ?></span></th>
                <th><span class="nobr"><?php echo $this->helper('sales')->__('Discount Amount') ?></span></th>
                <th class="last"><span class="nobr"><?php echo $this->helper('sales')->__('Row Total') ?></span></th>
            </tr>
        </thead>
        <?php $_items = $this->getItemsCollection() ?>
        <?php $i=0;
        $sellersubtotal=0;
        $sellershippingcharge = 0;
        $sellerdiscount_amount = 0;
        $sellertaxamount = 0;
        $sellerbasesubtotal=0;
        $sellerbaseshippingcharge = 0;
        $sellerbasediscount_amount = 0;
        $sellerbasetaxamount = 0; 
        $sellerorderdata = array();
        foreach ($_items as $_item):?>
        <?php	if($_roleId==$roleId){
         if(in_array($_item->getData("product_id"),$productIDs)):?>
            <?php if ($_item->getParentItem()) continue; else $i++;?>
            <tbody class="<?php echo $i%2?'even':'odd' ?>">
            <?php
               $sellersubtotal += $_item->getRowTotal();
               $sellerdiscount_amount += $_item->getDiscountAmount();
               $sellershippingcharge += $_item->getShippingCharge(); 
               $sellertaxamount += $_item->getTaxAmount(); 

               $sellerbasesubtotal += $_item->getBaseRowTotal();
               $sellerbasediscount_amount += $_item->getBaseDiscountAmount();
               $sellerbaseshippingcharge += $_item->getBaseShippingCharge(); 
               $sellerbasetaxamount += $_item->getBaseTaxAmount(); 
             ?>
                <?php echo $this->getItemHtml($_item) ?>
                <?php echo $this->getItemExtraInfoHtml($_item) ?>
            </tbody> 
        <?php endif;  
        }
        else
        { 
	
	?>
	 <?php if ($_item->getParentItem()) continue; else $i++;?>
            <tbody class="<?php echo $i%2?'even':'odd' ?>">
                <?php echo $this->getItemHtml($_item) ?>
                <?php echo $this->getItemExtraInfoHtml($_item) ?>
            </tbody>
<?php }?>
        <?php endforeach; ?>
        <?php
            $sellerorderdata['sellersubtotal'] = $sellersubtotal;
            $sellerorderdata['sellershippingcharge'] = $sellershippingcharge;
            $sellerorderdata['sellerdiscountamount'] = $sellerdiscount_amount;
            $sellerorderdata['sellertaxamount'] = $sellertaxamount; 
            
            $sellerorderdata['sellerbasesubtotal'] = $sellerbasesubtotal;
            $sellerorderdata['sellerbaseshippingcharge'] = $sellerbaseshippingcharge; 
            $sellerorderdata['sellerbasediscountamount'] = $sellerbasediscount_amount;
            $sellerorderdata['sellerbasetaxamount'] = $sellerbasetaxamount;
            Mage::getSingleton('adminhtml/session')->setSellerOrderData($sellerorderdata);
        ?>
    </table>
  </div>
</div>
<br />
