<div class="entry-edit">
    <div class="entry-edit-head">
        <div style="float: right;"><?php echo $this->getButtonsHtml() ?></div>
        <h4 class="fieldset-legend <?php echo ($this->getHeaderCssClass()) ? $this->getHeaderCssClass().' icon-head' : '' ?>"><?php echo $this->getHeaderText() ?></h4>
    </div>
    <div class="fieldset">
		<form action="<?php echo Mage::helper("adminhtml")->getUrl("*/*/"); ?>" method="post">
		 <?php echo $this->getBlockHtml('formkey')?>
		<div style="margin-bottom: 10px;"><label for="name">Search By Name / UPC / ESIN </label>
		<?php 
		if($this->getRequest()->getPost("search_product")){
		$searchq = $this->getRequest()->getPost("search_product");
		}elseif(Mage::getSingleton('core/session')->getSearchProductSession()){
		$searchq = Mage::getSingleton('core/session')->getSearchProductSession();
		}else{
		$searchq = '';
		}
		?>
		<input pattern=".{4,}" required title="Minimum 4 Characters Require"  name="search_product" value="<?php echo $searchq; ?>" class=" required-entry input-text required-entry" type="text" autofocus>
		<button title="Search Product" id="existingGridSearchQry" type="button" class="scalable task"  onclick="submitesinform()" style="">
		<span>Search Product</span>
		</button>
		<input id="submit_handler" type="submit" style="display: none">	
		</div>
		</form>
		<form id="edit_form" action="<?php echo $this->getSaveUrl() ?>" method="post" enctype="multipart/form-data">
    <?php echo $this->getBlockHtml('formkey')?>

        <?php echo $this->getChildHtml('', true, true) ?>
        </form>
    </div>
</div>
<script>
function submitesinform() {
    document.getElementById('submit_handler').click();
}
</script>
