<?php $_item = $this->getItem() ?>
<tbody>
    <tr>
        <td class="cell-content product-info">
            <p class="product-name"><?php echo $this->escapeHtml($_item->getName()) ?></p>
             <?php 
            if($_item->getSellerId()){
                ?>
                <p class="seller" style="margin:0px;padding:0px;"><?php echo $this->__('Seller'); ?>: 
                <?php 
                    $storename = Mage::helper('marketplace')->sellerstorenameFromSellerId($_item->getSellerId());
                    echo $storename;
                ?>
                </p>
                <?php 
            }
            ?>
            <?php if ($this->getItemOptions()): ?>
                <dl style="margin:0; padding:0;">
                    <?php foreach ($this->getItemOptions() as $option): ?>
                        <dt><strong><em><?php echo $option['label'] ?></em></strong></dt>
                        <dd style="margin:0; padding:0 0 0 9px;"><?php echo nl2br($option['value']) ?></dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <?php $addInfoBlock = $this->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock) :?>
                <?php echo $addInfoBlock->setItem($_item->getOrderItem())->toHtml(); ?>
            <?php endif; ?>
            <?php echo $this->escapeHtml($_item->getDescription()) ?>
        </td>
        <td class="cell-content align-center"><?php echo $this->escapeHtml($this->getSku($_item)) ?></td>
        <td class="cell-content align-right"><?php echo $_item->getQty()*1 ?></td>
    </tr>
</tbody>
