<?php $enableTrackUrOrder = Mage::getStoreConfig('trackyourorder/general/activate_fuel_trackorder_enable');  ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $_orders = $this->getOrders(); ?>
<div class="page-title">
    <h1><?php echo $this->__('My Orders') ?></h1>
</div>
<?php echo $this->getPagerHtml(); ?>
<?php if($_orders->getSize()): ?>
<!--  shown table -->
<table class="data-table" id="my-orders-table">
    <col width="1" />
    <col width="1" />
    <col />
    <col width="1" />
    <col width="1" />
    <col width="1" />
    <thead>
        <tr>
            <th><?php echo $this->__('Order #') ?></th>
            <th><?php echo $this->__('Date') ?></th>
            <th><?php echo $this->__('Ship To') ?></th>
            <th><span class="nobr"><?php echo $this->__('Order Total') ?></span></th>
            <th><span class="nobr"><?php echo $this->__('Order Status') ?></span></th>            
            <th><span class="nobr"><?php echo $this->__('Action') ?></span></th>
        </tr>
    </thead>
    <tbody>
        <?php $_odd = ''; ?>
        <?php foreach ($_orders as $_order): ?>
        <?php $orderId = Mage::helper('core')->encrypt($_order->getRealOrderId()); 
        $_orderId =  $_order->getRealOrderId();
        ?>
        <tr>        
            <td><span class="trackorder-bg"><a href="<?php echo $this->getUrl("trackyourorder/index/trackordersummary")."orderId/$_orderId"; ?>" title="<?php echo $this->__('Track your order'); ?>"><?php echo $_order->getRealOrderId() ?></a></span></td>
            <td><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
            <td><?php echo $_order->getShippingAddress() ? $this->htmlEscape($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
            <td><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
            <td><em><?php echo $_order->getStatusLabel() ?></em></td>            
            <td class="a-center">
                <span class="nobr"><a href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $this->__('View Order') ?></a>
                    <?php if($enableTrackUrOrder > 0 ){ ?>
                        <span class="separator">|</span>
                        <a  href="<?php echo $this->getUrl('trackyourorder/index/trackordersummary') ?>orderId/<?php echo $_order->getRealOrderId() ?>" rel="<?php echo $_order->getId() ?>" title="<?php echo $this->__('Track your order'); ?>"><?php echo $this->__('Track Order') ?></a>
                        <?php } ?>
                    <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                    <span class="separator">|</span> <a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-reorder"><?php echo $this->__('Reorder') ?></a>
                <?php endif ?>
                </span>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('my-orders-table');</script>
<?php echo $this->getPagerHtml(); ?>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
    
<?php endif ?>
