<div class="box-account box-recent">
<?php $_orders = $this->getOrders(); ?>
    <div class="box-head">
        <h2><?php echo $this->__('Recent Orders') ?></h2>
        <?php if( sizeof($_orders->getItems()) > 0 ): ?><a href="<?php echo $this->getUrl('sales/order/history') ?>"><?php echo $this->__('View All') ?></a><?php endif; ?>
    </div>
<?php if( sizeof($_orders->getItems()) > 0 ): ?>
    <table class="data-table" id="my-orders-table">
    <col width="1" />
    <col width="1" />
    <col />
    <col width="1" />
    <col width="1" />
    <col width="1" />
        <thead>
            <tr>
                <th><?php echo $this->__('Order #') ?></th>
                <th><?php echo $this->__('Date') ?></th>
                <th><?php echo $this->__('Ship To') ?></th>
                <th><span class="nobr"><?php echo $this->__('Order Total') ?></span></th>
                <th><?php echo $this->__('Status') ?></th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php /* Enable Track your order */
                  $enableTrackUrOrder = Mage::getStoreConfig('trackyourorder/general/activate_fuel_trackorder_enable'); 
                 
                  foreach ($_orders as $_order): 
              ?>
                <tr>
                    
                  <?php if($enableTrackUrOrder > 0 ){ ?>
                        <td>
                            <span class="trackorder-bg"><a  href="<?php echo $this->getUrl('trackyourorder/index/trackordersummary') ?>orderId/<?php echo $_order->getRealOrderId() ?>" rel="<?php echo $_order->getId() ?>" title="<?php echo $this->__('Track your order'); ?>"><?php echo $_order->getRealOrderId() ?></a></span>
                        </td>
                   <?php } else {  ?>
                        <td><?php echo $_order->getRealOrderId() ?></td>
               <?php    } ?>
                    
                    <td><span class="nobr"><?php echo $this->formatDate($_order->getCreatedAtStoreDate()) ?></span></td>
                    <td><?php echo $_order->getShippingAddress() ? $this->htmlEscape($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                    <td><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
                    <td><em><?php echo $_order->getStatusLabel() ?></em></td>
                    <td class="a-center">
                        <span class="nobr">
                        <a href="<?php echo $this->getViewUrl($_order) ?>"><?php echo $this->__('View Order') ?></a>
                        <?php if($enableTrackUrOrder > 0 ){ ?>
                        <span class="separator">|</span>
                        <a  href="<?php echo $this->getUrl('trackyourorder/index/trackordersummary') ?>orderId/<?php echo $_order->getRealOrderId() ?>" rel="<?php echo $_order->getId() ?>" title="<?php echo $this->__('Track your order'); ?>"><?php echo $this->__('Track Order') ?></a>
                        <?php } ?>
                        <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
                            <span class="separator">|</span> <a href="<?php echo $this->getReorderUrl($_order) ?>" class="link-reorder"><?php echo $this->__('Reorder') ?></a>
                        <?php endif ?>
                        </span>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('my-orders-table')</script>
<?php else: ?>
    <p><?php echo $this->__('You have placed no orders.'); ?></p>
<?php endif; ?>
</div>


