<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
<head>
	<?php 
    $isSecure = Mage::app()->getStore()->isCurrentlySecure();
    $baseurl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);
    if($isSecure){
        $baseurl = Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true );    
    } 
    ?>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php
		$storename = Mage::getStoreConfig('general/store_information/name');
		if(trim($storename)=='')
			$storename = '';
		else
			$storename = ' - '.$storename;
    ?>
    <title><?php echo Mage::helper('adminhtml')->__('Forgot Password').$storename; ?></title>
    <?php 
    $button = Mage::getStoreConfig('marketplace_setting/sellerpanelcolor/maincolor');
    $textcolor = Mage::getStoreConfig('marketplace_setting/sellerpanelcolor/textcolor');
    $texthovercolor = Mage::getStoreConfig('marketplace_setting/sellerpanelcolor/texthovercolor');
    ?>
    <style type="text/css">
    :root {
        --emi-button: <?php if($button){ echo $button;}else{echo '#0083d5';} ?>;
        --emi-textcolor:<?php if($textcolor){ echo $textcolor;}else{echo '#FFFFFF';} ?>;
        --emi-texthovercolor:<?php if($texthovercolor){ echo $texthovercolor;}else{echo '#FFFFFF';} ?>;
    }
    </style>
    <link type="text/css" rel="stylesheet" href="<?php echo $baseurl.'skin/adminhtml/default/default/reset.css'; ?>" media="all" />
    <link type="text/css" rel="stylesheet" href="<?php echo $baseurl.'skin/adminhtml/default/default/emipro/css/marketplace_admin.css'; ?>" media="all" /> 
    
    <?php
		$folderName = Mage_Adminhtml_Model_System_Config_Backend_Image_Favicon::UPLOAD_DIR;
        $storeConfig = Mage::getStoreConfig('design/head/shortcut_icon');
        $faviconFile = Mage::getBaseUrl('media') . $folderName . '/' . $storeConfig;
        $absolutePath = Mage::getBaseDir('media') . '/' . $folderName . '/' . $storeConfig;

        if(!is_null($storeConfig) && is_file($absolutePath)) {
            $url = $faviconFile;
        } else {
            $url = $baseurl.'skin/adminhtml/default/default/favicon.ico';
        }
    ?> 
    <link rel="icon" href="<?php echo $url; ?>" type="image/x-icon" /> 
    <link rel="shortcut icon" href="<?php echo $url; ?>" type="image/x-icon" />

    <script type="text/javascript" src="<?php echo $baseurl.'js/prototype/prototype.js'; ?>"></script>
    <script type="text/javascript" src="<?php echo $baseurl.'js/prototype/validation.js'; ?>"></script>
    <script type="text/javascript" src="<?php echo $baseurl.'js/mage/adminhtml/events.js'; ?>"></script>
    <script type="text/javascript" src="<?php echo $baseurl.'js/mage/adminhtml/form.js'; ?>"></script>
    <script type="text/javascript" src="<?php echo $baseurl.'js/scriptaculous/effects.js'; ?>"></script>
    <script type="text/javascript" src="<?php echo $baseurl;  ?>js/mage/captcha.js"></script>

    <!--[if IE]> <link rel="stylesheet" href="<?php echo $this->getSkinUrl('iestyles.css'); ?>" type="text/css" media="all" /> <![endif]-->
    <!--[if lt IE 7]> <link rel="stylesheet" href="<?php echo $this->getSkinUrl('below_ie7.css'); ?>" type="text/css" media="all" /> <![endif]-->
    <!--[if IE 7]> <link rel="stylesheet" href="<?php echo $this->getSkinUrl('ie7.css'); ?>" type="text/css" media="all" /> <![endif]-->
</head>
<body id="page-login">
    <style>
        .captcha-image{width:162px;}
        #captcha_backend_forgotpassword{width:290px !important;}
        .captcha_block li{list-style-type: none;}
        .captcha_block li input{margin:0px !important;}
        .captcha_block{padding-bottom: 10px;}
        label[for=captcha_backend_forgotpassword]{margin: 10px 0px 0px;display: block;}
    </style>
<?php 
		if(Mage::getStoreConfig('marketplace_setting/marketplace/logo'))
        { 
            $logourl = Mage::getBaseUrl('media') .'seller/'. Mage::getStoreConfig('marketplace_setting/marketplace/logo');
        }else{
            $logosrc = Mage::getStoreConfig('design/header/logo_src');
            $logosrcsmall = Mage::getStoreConfig('design/header/logo_src_small');
            if($logosrc!=''){
                $logourl = $logosrc;
            }else{
                $logourl = $logosrcsmall;
            }
            $logoalt = Mage::getStoreConfig('design/header/logo_alt'); 
            $logourl = $this->getSkinUrl($logourl);
        } 
	?> 
        <div>
            <a href="<?php echo Mage::getBaseUrl();?>"><img class="admin_logo" width="200px" src="<?php echo $logourl;?>" alt="<?php echo $logoalt;?>"/></a>
        </div>
    <div class="login-container" style="width:420px !important">
        <div class="login-box">
            <form method="post" action="<?php echo $baseurl;?>marketplace/sellerlogin/forgotpassword/" id="loginForm">
       <input type="hidden" name="seller" value="1">
                <fieldset class="login-form">
                    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
                    <h2><?php echo Mage::helper('adminhtml')->__('Forgot your user name or password?'); ?></h2>
                    <div id="messages">
                     <?php
                        $params = Mage::app()->getFrontController()->getRequest()->getParams();
                        if(isset($params['captcha']))
                        {
                            echo '<div style="color:red;font-weight:bold;padding-bottom:10px">'. Mage::helper('adminhtml')->__('Invalid Captcha.') . '</div>'; 
                        }
                    ?>                        
                    </div>
                    <div class="input-box forgot-password"><label for="email"><?php echo Mage::helper('adminhtml')->__('Email Address:'); ?></label><br />
                        <input type="text" id="email" name="email" value="" class="required-entry input-text forgot-password validate-email" style="width:290px;margin-bottom:0px;" />
                    </div>
                    <div class="captcha_block">
                    <?php 
                        $enablecaptcha = Mage::getStoreConfig('marketplace_setting/marketplace/forgotpasswordcaptcha');
                        if($enablecaptcha) 
                        {
                            echo $this->getChildHtml('captcha');        
                        }   
                    ?> 
                    </div>    
                    <div class="clear"></div>
                    <div class="form-buttons">
                        <a class="left" href="<?php echo $this->getUrl('marketplace/sellerlogin'); ?>">&laquo; <?php echo Mage::helper('adminhtml')->__('Back to Login'); ?></a>
                        <button class="forgot-password form-button" style="width:136px;height:30px;float:right;cursor:pointer" onclick="loginForm.submit()" type="button"><span><span><span><?php echo Mage::helper('adminhtml')->__('Retrieve Password'); ?></span></span></span></button>
                    </div>
                </fieldset>                
            </form>
            <div class="bottom"></div>
            <script type="text/javascript">
                 var loginForm = new varienForm('loginForm');
            </script>
        </div>
    </div>
</body>
</html>

