<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
    <head>
        <?php $baseurl = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);?>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?php echo Mage::helper('adminhtml')->__('Reset a Password'); ?></title>
        <?php 
    $button = Mage::getStoreConfig('marketplace_setting/sellerpanelcolor/maincolor');
    $textcolor = Mage::getStoreConfig('marketplace_setting/sellerpanelcolor/textcolor');
    $texthovercolor = Mage::getStoreConfig('marketplace_setting/sellerpanelcolor/texthovercolor');
    ?>
    <style type="text/css">
    :root {
        --emi-button: <?php if($button){ echo $button;}else{echo '#0083d5';} ?>;
        --emi-textcolor:<?php if($textcolor){ echo $textcolor;}else{echo '#FFFFFF';} ?>;
        --emi-texthovercolor:<?php if($texthovercolor){ echo $texthovercolor;}else{echo '#FFFFFF';} ?>;
    }
    </style>
        <link type="text/css" rel="stylesheet" href="<?php echo $baseurl.'skin/adminhtml/default/default/reset.css'; ?>" media="all" />
        <link type="text/css" rel="stylesheet" href="<?php echo $baseurl.'skin/adminhtml/default/default/emipro/css/marketplace_admin.css'; ?>" media="all" />

         <?php
        $folderName = Mage_Adminhtml_Model_System_Config_Backend_Image_Favicon::UPLOAD_DIR;
        $storeConfig = Mage::getStoreConfig('design/head/shortcut_icon');
        $faviconFile = Mage::getBaseUrl('media') . $folderName . '/' . $storeConfig;
        $absolutePath = Mage::getBaseDir('media') . '/' . $folderName . '/' . $storeConfig;

        if(!is_null($storeConfig) && is_file($absolutePath)) {
            $url = $faviconFile;
        } else { 
            $url = $baseurl.'skin/adminhtml/default/default/favicon.ico';
        }
    ?> 
    <link rel="icon" href="<?php echo $url; ?>" type="image/x-icon" /> 
    <link rel="shortcut icon" href="<?php echo $url; ?>" type="image/x-icon" />

    <script type="text/javascript" src="<?php echo $baseurl.'js/prototype/prototype.js'; ?>"></script>
    <script type="text/javascript" src="<?php echo $baseurl.'js/prototype/validation.js'; ?>"></script>
    <script type="text/javascript" src="<?php echo $baseurl.'js/mage/adminhtml/events.js'; ?>"></script>
    <script type="text/javascript" src="<?php echo $baseurl.'js/mage/adminhtml/form.js'; ?>"></script>
    <script type="text/javascript" src="<?php echo $baseurl.'js/scriptaculous/effects.js'; ?>"></script>

    <!--[if IE]> <link rel="stylesheet" href="<?php echo $this->getSkinUrl('iestyles.css'); ?>" type="text/css" media="all" /> <![endif]-->
    <!--[if lt IE 7]> <link rel="stylesheet" href="<?php echo $this->getSkinUrl('below_ie7.css'); ?>" type="text/css" media="all" /> <![endif]-->
    <!--[if IE 7]> <link rel="stylesheet" href="<?php echo $this->getSkinUrl('ie7.css'); ?>" type="text/css" media="all" /> <![endif]-->
    </head>
    <body id="page-login">
            <div>
            <?php 
                if(Mage::getStoreConfig('marketplace_setting/marketplace/logo'))
                { 
                    $logourl = Mage::getBaseUrl('media') .'seller/'. Mage::getStoreConfig('marketplace_setting/marketplace/logo');
                }else{
                    $logosrc = Mage::getStoreConfig('design/header/logo_src');
                    $logosrcsmall = Mage::getStoreConfig('design/header/logo_src_small');
                    if($logosrc!=''){
                        $logourl = $logosrc; 
                    }else{
                        $logourl = $logosrcsmall;
                    }
                    $logoalt = Mage::getStoreConfig('design/header/logo_alt'); 
                    $logourl = $this->getSkinUrl($logourl);
                }
            ?>
                <a  href="<?php echo Mage::getBaseUrl(); ?>">  
                <img class="admin_logo" width="200px" src="<?php echo $logourl;?>" alt="<?php echo $logoalt;?>"/>
                </a>
            </div>
        <div class="login-container">
            <div class="login-box">
            
                <form method="post" action="<?php echo $this->getUrl('adminhtml/index/resetpasswordpost', array('_query' => array('id' => $this->getRequest()->getParam('id',0), 'token' => $this->getRequest()->getParam('token'))));  ?>" id="reset-password-form">
                    <fieldset class="login-form">
                        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
                        <h2><?php echo Mage::helper('adminhtml')->__('Reset a Password'); ?></h2>
                        <div id="messages">
                            <?php echo $this->getMessagesBlock()->toHtml(); ?>
                        </div>
                        <div class="input-box" style="margin:10px 0px;">
                            <label for="password"><em class="required">*</em> <?php echo $this->__('New Password'); ?></label>
                            <br />
                            <input type="password" class="input-text required-entry validate-admin-password" name="password" id="password" style="margin:5px 0px;"/>
                        </div>
                        <div class="input-box" style="margin:10px 0px;">
                            <label for="confirmation"><em class="required">*</em> <?php echo $this->__('Confirm New Password'); ?></label>
                            <br />
                            <input type="password" class="input-text required-entry validate-cpassword" name="confirmation" id="confirmation"  style="margin:5px 0px;" />
                        </div>
                        <div class="clear"></div>
                        <div class="form-buttons">
                            <a class="left" href="<?php echo $this->getUrl('adminhtml', array('_nosecret' => true)) ?>">&laquo; <?php echo Mage::helper('adminhtml')->__('Back to Login'); ?>
                            </a>
                            <button type="submit" style="width:136px;height:30px;float:right;cursor:pointer"  title="<?php echo Mage::helper('adminhtml')->__('Reset Password'); ?>" class="forgot-password form-button">
                                <span><span><span>
                                        <?php echo Mage::helper('adminhtml')->__('Reset Password'); ?>
                                </span></span></span>
                            </button>
                        </div>
                    </fieldset>
                </form>
                <div class="bottom"></div>
                <script type="text/javascript">
                    var resetPasswordForm = new varienForm('reset-password-form');
                </script>
            </div>
        </div>
    </body>
</html>
