<?php $_order = $this->getOrder() ?>
<h1><?php echo $this->__('Order #%s', $_order->getRealOrderId()) ?></h1>
<p class="order-date"><?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAtStoreDate(), 'long')) ?></p>
<?php $_invoice = $this->getInvoice() ?>
<?php if($_invoice): ?>
    <?php $_invoices = array($_invoice); ?>
<?php else: ?>
    <?php $_invoices = $_order->getInvoiceCollection() ?>
<?php endif; ?>
<?php foreach ($_invoices as $_invoice): ?>
    <?php 
    if($_invoice->getSellerId())
    {
         $sellerdetail = Mage::helper('marketplace')->getSellerInfo($_invoice->getSellerId());
        ?>
            <?php if($sellerdetail->getId()){ ?>
                 <div style="margin:10px 0px;">
                    <?php if(trim($sellerdetail->getCompanyLogo())!=''){ ?>
                    <div>
                        <img src="<?php echo Mage::getBaseUrl('media').$sellerdetail->getCompanyLogo();?>" style="max-height:50px;">
                    </div>
                    <?php } ?>
                    <?php if(trim($sellerdetail->getStoreName())!=''){ ?>
                    <h4 style="margin-top:10px;"><?php echo $this->__('Sold By').' : '.$sellerdetail->getStoreName(); ?>
                    </h4>
                    <?php }?>
                    <?php if(trim($sellerdetail->getVatNumber())!=''){ ?>
                    <div>
                        <?php echo $this->__('VAT Number').' : '.$sellerdetail->getVatNumber(); ?>
                    </div>
                    <?php } ?>
                    <div>
                        <?php echo $this->__('Address').' : '.$sellerdetail->getStreet1().' '.$sellerdetail->getStreet2().', '.$sellerdetail->getCity().', '.$sellerdetail->getPostcode().',     Telephone : '.$sellerdetail->getTelephone(); ?>
                    </div>
                </div>
        <?php
            }
    }
    ?>
    <h2 class="h2"><?php echo $this->__('Invoice #%s', $_invoice->getIncrementId()) ?></h2>
    <div class="col2-set">
        <div class="col-1">
        <?php if (!$_order->getIsVirtual()): ?>
            <h3><?php echo $this->__('Shipping Address') ?></h3>
            <?php $_shipping = $_invoice->getShippingAddress() ?>
            <address><?php echo $_shipping->format('html') ?></address>
        </div>
        <div class="col-2">
        <?php endif; ?>
            <h3><?php echo $this->__('Billing Address') ?></h3>
            <?php $_billing = $_invoice->getbillingAddress() ?>
            <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
        </div>
        <?php if (!$_order->getIsVirtual()): ?>
    </div>
    <div class="col2-set">
        <div class="col-1">
            <h3><?php echo $this->__('Shipping Method') ?></h3>
             <?php echo $this->escapeHtml($_order->getShippingDescription()) ?>
        </div>
        <?php endif; ?>
        <div class="col-2">
            <h3><?php echo $this->__('Payment Method') ?></h3>
            <?php echo $this->getPaymentInfoHtml() ?>
        </div>
    </div>
    <h3><?php echo $this->__('Items Invoiced') ?></h3>
    <table class="data-table" id="my-invoice-table-<?php echo $_invoice->getId(); ?>">
        <col />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <thead>
            <tr>
                <th><?php echo $this->__('Product Name') ?></th>
                <th><?php echo $this->__('SKU') ?></th>
                <th class="a-right"><?php echo $this->__('Price') ?></th>
                <th class="a-center"><span class="nobr"><?php echo $this->__('Qty Invoiced') ?></span></th>
                <th class="a-right"><?php echo $this->__('Subtotal') ?></th>
            </tr>
        </thead>
        <tfoot>
            <?php echo $this->getInvoiceTotalsHtml($_invoice)?>
        </tfoot>
        <?php $_items = $_invoice->getItemsCollection(); ?>
        <?php $_count = $_items->count(); ?>
        <?php foreach ($_items as $_item): ?>
        <?php if ($_item->getOrderItem()->getParentItem()) continue; ?>
        <tbody>
            <?php echo $this->getItemHtml($_item) ?>
        </tbody>
        <?php endforeach; ?>
    </table>
    <script type="text/javascript">decorateTable('my-invoice-table-<?php echo $_invoice->getId(); ?>', {'tbody' : ['odd', 'even'], 'tbody tr' : ['first', 'last']})</script>
<?php endforeach; ?>
<script type="text/javascript">window.print();</script>
