<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>
<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {
        $_imgHtml = '<p class="category-image"><img src="'.$_imgUrl.'" alt="'.$this->escapeHtml($_category->getName()).'" title="'.$this->escapeHtml($_category->getName()).'" /></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>
<div class="page-title category-title">
    <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
        <a href="<?php echo $this->getRssLink() ?>" class="link-rss"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
    <?php endif; ?>
    <h1><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
</div>

<?php echo $this->getMessagesBlock()->toHtml() ?>

<?php if($_imgUrl): ?>
    <?php echo $_imgHtml ?>
<?php endif; ?>

<?php if($_description=$this->getCurrentCategory()->getDescription()): ?>
    <div class="category-description std">
        <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
    </div>
    <?php endif; ?>

<?php
	$id = $this->getRequest()->getParam('id');
	$sellerurl=''; 
	if($id)
	{
		$seller = Mage::getModel('marketplace/seller')->load($id,'seller_id');
		if(isset($seller)&& !empty($seller)){
			$banner = $seller['banner'];
			if($banner!='')
			{
				$seller_banner = Mage::getModel('cms/block')
				->setStoreId(Mage::app()->getStore()->getId())
				->load('seller_product_listing_banner');
				$_img_src = array();
				$baseurl =  Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
				$_img_src['imgsrc'] = $baseurl.$banner;
				$_filter = Mage::getModel('cms/template_filter');
				$_filter->setVariables($_img_src);
				echo  $_filter->filter($seller_banner->getContent());
			} 
		}
	}
?>

<?php if($this->isContentMode()): ?>
    <?php //echo $this->getCmsBlockHtml() ?>

<?php elseif($this->isMixedMode()): ?>
    <?php //echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>
