<?php
    $store = Mage::app()->getStore();
    $code  = $store->getCode();
	$productBlock = $this->getLayout()->createBlock('catalog/product_price');
	$_productCollection = $this->bestSellerCollection();
    $_helper = $this->helper('catalog/output');
    $_image_helper = $this->helper('catalog/image');

    $aspect_ratio = $this->getData("aspect_ratio");
    if($aspect_ratio == null) {
        $aspect_ratio = Mage::getStoreConfig("porto_settings/category/aspect_ratio",$code);
    }
    $ratio_width = $this->getData("image_width");
    if(!$ratio_width) {
        $ratio_width = Mage::getStoreConfig("porto_settings/category/ratio_width",$code);
    }
    $ratio_height = $this->getData("image_height");
    if(!$ratio_height) {
        $ratio_height = Mage::getStoreConfig("porto_settings/category/ratio_height",$code);
    }
    
    if(!$ratio_width)
        $ratio_width = 300;
    if(!$ratio_height)
        $ratio_height = 400;
        
    $lazy_owl = $this->getData("lazy_owl");
    if(!$lazy_owl)
        $lazy_owl = 0;
?>
<div id="brandslogo">
<h1><?php echo $this->__('Best Selling Products') ?></h1>
    <div class="filter-products">
         <div class="products owl-carousel">
    <?php
        foreach($_productCollection as $_product):
			$product = $_product;
	?>
	<div class="item"><div class="item-area">
	<div class="product-image-area">
		<div class="loader-container">
			<div class="loader">
				<i class="ajax-loader medium animate-spin"></i>
			</div>
		</div>
		 <?php
			if( Mage::getStoreConfig("quickview/general/enableview", $code) ){
				$base_url = $this->getUrl();
				if(strpos($base_url,'?')!==false)
					$base_url = explode("?",$this->getUrl());
				if(is_array($base_url))
					$base_url = $base_url[0];
				$base_url .= "quickview/index/view/";
				$quickview_url = $base_url."id/".$_product->getId();
				?>
				<a href="<?php echo $quickview_url; ?>" class="quickview-icon"><i class="icon-export"></i><span><?php echo $this->__("Quick View"); ?></span></a>
			<?php
			}
			?>
		<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
		<?php
			if(Mage::getStoreConfig("porto_settings/category/alternative_image", $code)){
		?>
			<img class="defaultImage <?php if($lazy_owl): ?>lazyOwl<?php endif; ?>" <?php if($lazy_owl): ?>data-<?php endif; ?>src="<?php if($aspect_ratio):?><?php echo $_image_helper->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($ratio_width);?><?php else: ?><?php echo $_image_helper->init($_product, 'small_image')->resize($ratio_width,$ratio_height); ?><?php endif; ?>" width="<?php echo $ratio_width; ?>" <?php if(!$aspect_ratio):?>height="<?php echo $ratio_height; ?>"<?php endif; ?> alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
		<?php
			} else {
		?>
			<img <?php if($lazy_owl): ?>class="lazyOwl" data-<?php endif; ?>src="<?php if($aspect_ratio):?><?php echo $_image_helper->init($_product, 'small_image')->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($ratio_width);?><?php else: ?><?php echo $_image_helper->init($_product, 'small_image')->resize($ratio_width,$ratio_height); ?><?php endif; ?>" width="<?php echo $ratio_width; ?>" <?php if(!$aspect_ratio):?>height="<?php echo $ratio_height; ?>"<?php endif; ?> alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/>
		<?php
			}
		?>
		</a>
		<?php                         
			$sale_label = false;

			// Get the Special Price
			$specialprice = $product->getFinalPrice();
			$orgprice = $product->getPrice();
			// Get the Special Price FROM date
			$now = date("Y-m-d");
			$specialPriceFromDate = substr($product->getSpecialFromDate(),0,10);
			// Get the Special Price TO date
			$specialPriceToDate = substr($product->getSpecialToDate(),0,10);
			// Get Current date
			$today =  time();
		 
			if ($specialprice<$orgprice){
				$save_percent = 100-round(($specialprice/$orgprice)*100);
				if ($specialPriceToDate != '' || $specialPriceFromDate != ''){
				if (($specialPriceToDate != '' && $specialPriceFromDate != '' && $now>=$specialPriceFromDate && $now<=$specialPriceToDate) || ($specialPriceToDate == '' && $now >=$specialPriceFromDate) || ($specialPriceFromDate == '' && $now<=$specialPriceToDate)){
					if(Mage::getStoreConfig("porto_settings/product_label/sale", $code)){
						$sale_label = true;
		?>
					<div class="product-label" style="right: 10px;"><span class="sale-product-icon"><?php if(Mage::getStoreConfig("porto_settings/product_label/sale_label_type", $code)):?><?php echo "-".$save_percent."%"; ?><?php else: ?><?php echo Mage::getStoreConfig("porto_settings/product_label/sale_label_text", $code);?><?php endif; ?></span></div>
		<?php       
					}
				}
			}
			}
		?>
		<?php
			$now = date("Y-m-d");
			$newsFrom= substr($product->getData('news_from_date'),0,10);
			$newsTo=  substr($product->getData('news_to_date'),0,10);
			if ($newsTo != '' || $newsFrom != ''){
				if (($newsTo != '' && $newsFrom != '' && $now>=$newsFrom && $now<=$newsTo) || ($newsTo == '' && $now >=$newsFrom) || ($newsFrom == '' && $now<=$newsTo))
				{
					if(Mage::getStoreConfig("porto_settings/product_label/new", $code)){
			?> 
					<div class="product-label" style="right: 10px; <?php echo ($sale_label)?"top: 40px;":""; ?>"><span class="new-product-icon"><?php echo Mage::getStoreConfig("porto_settings/product_label/new_label_text", $code);?></span></div>
			<?php 
					}
				}
			}
		?>
	</div>
	<div class="details-area">
		<?php if(!Mage::getStoreConfig("porto_settings/category_grid/move_title", $code)):?>
			<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
		<?php endif;?>
		<?php if(Mage::getStoreConfig("porto_settings/category/rating_star", $code)):?>
		<?php if (Mage::helper('catalog')->isModuleEnabled('Mage_Review')): ?>
		<?php 
			$review_html = $this->getReviewsSummaryHtml($product, 'short');
			if($review_html){
				echo $review_html;
			}else{
		?>
			<div class="ratings">
				<div class="rating-box">
					<div class="rating" style="width:0"></div>
				</div>
			</div>
		<?php                            
			}
		?>
		<?php else: ?>
			<div class="ratings">
				<div class="rating-box">
					<div class="rating" style="width:0"></div>
				</div>
			</div>
		<?php endif; ?>
		<?php endif; ?>
		<?php if(Mage::getStoreConfig("porto_settings/category_grid/move_title", $code)):?>
			<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
		<?php endif;?>
		<?php echo $productBlock->getPriceHtml($_product, true) ?>
		<?php if(Mage::getStoreConfig("porto_settings/category/actions", $code)):?>
		<div class="actions">
			<?php if($product->isSaleable()): ?>
				<?php  if ( !($product->getTypeInstance(true)->hasOptions($product) || $product->isGrouped()) ) :  ?>
					<a href="<?php if(!Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code) && !Mage::getStoreConfig("porto_settings/category/qty_field", $code)): ?><?php echo Mage::helper('checkout/cart')->getAddUrl($_product) ?><?php else: ?>javascript:void(0)<?php endif; ?>" class="addtocart" title="<?php echo $this->__('Add to Cart') ?>" <?php if(Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code)):?>onclick="setLocationAjax(this,'<?php echo Mage::helper('checkout/cart')->getAddUrl($_product) ?>','<?php echo $_product->getId(); ?>')"<?php elseif(Mage::getStoreConfig("porto_settings/category/qty_field", $code)): ?>onclick="document.getElementById('addtocart_form_<?php echo $_product->getId(); ?>').submit()"<?php endif; ?>><i class="icon-cart"></i><span>&nbsp;<?php echo $this->__('Add to Cart') ?></span></a>
				<?php else : ?>
					<a href="<?php if(Mage::getStoreConfig("ajaxcart/addtocart/enablecategory", $code)):?>javascript:showOptions('<?php echo $_product->getId()?>')<?php else: ?><?php echo Mage::helper('checkout/cart')->getAddUrl($_product) ?><?php endif; ?>" class="addtocart" title="<?php echo $this->__('Add to Cart') ?>"><i class="icon-cart"></i><span>&nbsp;<?php echo $this->__('Add to Cart') ?></span></a>
					<a href='<?php echo $this->getUrl('ajaxcart/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'>Options</a>
				<?php endif;?>
			<?php else: ?>
				<a href="javascript:void(0);" class="addtocart outofstock" title="<?php echo $this->__('Out of stock') ?>"><?php echo $this->__('Out of stock') ?></span></a>
			<?php endif; ?>
			
			<div class="clearer"></div>
		</div>
		<?php endif; ?>
	</div></div></div>
		<?php endforeach; ?>
        </div>
    </div>
</div>
<script type="text/javascript">
  jQuery(function($){
    $("#brandslogo .filter-products .owl-carousel").owlCarousel({lazyLoad: true,    itemsCustom: [ [0, 1], [320, 1], [480, 2], [768, 3], [992, 4], [1280, 5] ],    responsiveRefreshRate: 50,    slideSpeed: 200,    paginationSpeed: 500,    scrollPerPage: false,    stopOnHover: true,    rewindNav: true,    rewindSpeed: 600,    pagination: false,    navigation: true,    autoPlay: true,    navigationText:["<i class='icon-left-open'></i>","<i class='icon-right-open'></i>"]});
  });
</script>