<meta name="google-site-verification" content="FpKVuNiJKbaQZyeJmQ4NGPUYMJHORItLgI7xCiqQgU8" />
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<?php 
//Meta informations
$meta_title = $this->getMetaTitle() ? $this->getMetaTitle() : $this->getTitle(); 
$meta_description = $this->getMetaDescription() ? $this->getMetaDescription() : $this->getDescription();
?>
<title><?php echo htmlspecialchars($meta_title) ?></title>
<meta name="description" content="<?php echo htmlspecialchars($meta_description) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<!-- og tags for SEO -->
<?php $_product = Mage::registry('current_product'); ?>
<?php if ($_product) { ?>
	<meta property="og:title" content="<?php echo htmlspecialchars($_product->getName())?>" />
	<meta property="og:type" content="product" />
    <meta property="og:description" content="<?php echo htmlspecialchars($_product->getDescription())?>" />
	<meta property="og:url" content="<?php echo $_product->getProductUrl();?>" />
    <meta property="og:image" content="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')?>" />
	<meta property="og:image:width" content="450"/>
	<meta property="og:image:height" content="450"/>
	<link rel="image_src" type="image/jpg" href="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')?>" />
	<meta property="og:site_name" content="<?php echo Mage::app()->getStore()->getName(); ?>" />
	<meta property="fb:app_id" content="156296244949559" />
<?php } else {?>
	<meta property="og:title" content="ECOMMERCE PLATFORM & CONNECTING OEM'S & BUYERS ACROSS THE GLOBE" />
	<meta property="og:description" content="ECOMMERCE PLATFORM & CONNECTING OEM'S & BUYERS ACROSS THE GLOBE."/>
	<meta property="og:url" content="<?php echo $this->getUrl(''); ?>" />
	<meta property="og:image" content="<?php echo $this->getSkinUrl('images/og.png') ?>" />
	<meta property="og:image:width" content="450"/>
	<meta property="og:image:height" content="450"/>
	<link rel="image_src" type="image/jpg" href="<?php echo $this->getSkinUrl('images/og.png') ?>" />
	<meta property="og:site_name" content="<?php echo Mage::app()->getStore()->getName(); ?>" />
	<meta property="fb:app_id" content="156296244949559" />
<?php }?>
<!-- og tags for SEO -->
<!-- Theme Configuration -->
<?php
    $theme = Mage::helper('porto');
    $charSubset = '&subset=latin';
    $d = $theme->getCfgSectionDesign();
    $s = $theme->getCfgSectionSettings();
	if(!isset($s['general']['disable_responsive']) || (isset($s['general']['disable_responsive']) && !$s['general']['disable_responsive'])){
?>	
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<?php } ?>
<link rel="icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>
<!-- Theme Configuration -->
<script type="text/javascript">
//<![CDATA[
if (typeof dailydealTimeCountersCategory == 'undefined') {
	var dailydealTimeCountersCategory = new Array();
	var i = 0;
}
//]]>
</script>