<?php
/**
 * Business FUel
 * Loading the Sociallogin.js file
 */
if (Mage::getStoreConfig ( 'sociallogin/general/enable_sociallogin' ) == 1 && ! Mage::helper ( 'customer' )->isLoggedIn ()) {
?>
  <script src="<?php echo Mage::getBaseUrl('js').'sociallogin/sociallogin.js'; ?>" type="text/javascript"></script>
<?php 
}
$currentCoreUrl = $this->helper('core/url')->getCurrentUrl();
/**
 * Checking for SSL in the base url for redirection starts
 */
$currentUrl = Mage::helper('core/url')->getCurrentUrl();
$secure=strstr($currentUrl,"https");
if($secure == true) { 
    $twitterRedirection=Mage::getUrl('sociallogin/index/twitterpost/',array('_secure'=>true));
    $loginRedirection=Mage::getUrl('sociallogin/index/customerloginpost/',array('_secure'=>true));
    $createRedirection=Mage::getUrl('sociallogin/index/createPost/' ,array('_secure'=>true));
	$verifyMobile = Mage::getUrl('sociallogin/index/verifyMobile/' ,array('_secure'=>true));
	$resendOtp = Mage::getUrl('sociallogin/index/resendOtp/' ,array('_secure'=>true));
    $forgotdirection=Mage::getUrl('sociallogin/index/forgotPasswordPost/' ,array('_secure'=>true)) ;
}else{
    $twitterRedirection=Mage::getUrl('sociallogin/index/twitterpost/') ;
    $loginRedirection=Mage::getUrl('sociallogin/index/customerloginpost/') ;
    $createRedirection=Mage::getUrl('sociallogin/index/createPost/') ;
	$verifyMobile=Mage::getUrl('sociallogin/index/verifyMobile/') ;
	$resendOtp = Mage::getUrl('sociallogin/index/resendOtp/');
    $forgotdirection=Mage::getUrl('sociallogin/index/forgotPasswordPost/')  ;
} 
/**
 * set session for URLs relink and Link
 */
Mage::getSingleton('customer/session')->setLink($currentCoreUrl);
/**
 * Checking social login module enabled or disabled
 */
$fbStatus = Mage::getStoreConfig('sociallogin/facebook/enable_fb');
$twitterStatus = Mage::getStoreConfig('sociallogin/twitter/enable_twitter');
$googleStatus = Mage::getStoreConfig('sociallogin/google/enable_google');
$enableStatus = Mage::getStoreConfig('sociallogin/general/enable_sociallogin');
$paypalStatus = Mage::getStoreConfig('sociallogin/paypal/enable_paypal');
$loggedIn = $this->helper("customer")->isLoggedIn();
$facebookappId = Mage::getStoreConfig('sociallogin/facebook/fbapp_id');
$enableDob = Mage::getStoreConfig('customer/address/dob_show');
$enableGender = Mage::getStoreConfig('customer/address/gender_show');
$enableVat = Mage::getStoreConfig('customer/address/taxvat_show');
$enableCaptcha = Mage::getStoreConfig('customer/captcha/enable');
$reqClass = 'class="required"';
$emImport = '<em>*</em>';
/**
 * Checking customer is already logged in the webiste and social login module is enabled
 */
if (!$loggedIn && $enableStatus == 1) {
    ?>   
    <div id="header_logo_Div" style="display: none;">
    <a class="closeLink" href="javascript:fuel_socialloginclose();">X</a>
        <div id="social_popup_main">
            <div id="socialpopup_main_div">	
                    <div id="login_block">   
								<div class="modal-header">
                            <h4><?php echo $this->__('Login'); ?></h4>
						</div>
						<div id="all_social_iconbtn">				                   
                        <?php if ($fbStatus == 1) { ?>                           
                            <a id='facebook_login' title="<?php echo $this->__('Facebook'); ?>" onclick='fblogin();'>
								<button type="button" class="fb_login inner_social_grid" name="send">
								<img id="facebooklogin" src="<?php echo $this->getSkinUrl('sociallogin/images/fb.png'); ?>" alt="loading please wait" />
								<img id="progress_image_facebooklogin" style="display: none" src="<?php echo $this->getSkinUrl('sociallogin/images/ajax-loader.gif'); ?>"alt="loading please wait" width="16" height="16" />
								</button>
							</a>
                            <?php }                              
                            if ($twitterStatus == 1) { ?>
                                <?php /* Twitter button */ ?>
                            <a onclick="show_hide_socialforms('4');" id="popup_twitter_email" title="<?php echo $this->__('Twitter'); ?>">
								<span class="t_icon_left icon_left_grid"></span>
								<button type="submit" class="twitter_login inner_social_grid"
										name="send"><?php echo $this->__('Twitter'); ?></button>
								<span class="t_icon_right icon_right_grid"></span></a>
                        <?php }                        
                        if ($googleStatus == 1) { ?>                           
                            <a onclick="javascript:location.href = '<?php echo Mage::getUrl('sociallogin/index/googlepost/') ?>'" title="<?php echo $this->__('Google+'); ?>">
								<button type="submit" class="google_login inner_social_grid" name="send">
								<img id="googlelogin" src="<?php echo $this->getSkinUrl('sociallogin/images/gplus.png'); ?>" alt="loading please wait"/>
								</button>
							</a>
                        <?php }
                        if ($paypalStatus == 1) {
                            $locale = Mage::app()->getLocale()->getLocaleCode();
                        ?>
                        <li id="payPalButton" title="<?php echo $this->__('Paypal'); ?>"></li>
                        <script src="https://www.paypalobjects.com/js/external/api.js"></script>
                        <script> 
                        paypal.use( ["login"], function(login) {
                         login.render ({
                         "appid": "<?php echo Mage::helper('sociallogin')->getPaypalClientId() ?>",
                         <?php if(Mage::helper('sociallogin')->isSandBox()) {?>
                         "authend": "sandbox",
                         <?php } ?>
                         "scopes": "openid profile email address phone https://uri.paypal.com/services/paypalattributes",
                         "containerid": "payPalButton",
                         "locale": "<?php echo $locale;?>",
                         "returnurl": "<?php echo Mage::getBaseUrl();?>sociallogin/paypallogin/"
                        	  });
                         });
                        </script>
                        <?php } ?>
                </div>	
                        <form id="form_login" action="<?php echo $loginRedirection; ?>" class="socialpopup_form">
						
							<div class="modal-body u_ad_modal_body_mod">
								<label for="mobile" class="required"><?php echo $this->__('Mobile Number'); ?>
									<em>*</em></label>
								<div class="socialpopup-input-box">
								<input type="text" name="mobile" placeholder="Enter your mobile number" id="mobile" class="input-text validate-number required-entry validate-length maximum-length-10 minimum-length-10 validate-digits"
																		  title="<?php echo $this->__('Mobile Number'); ?>" /></div>
								<label for="pass" class="required"><?php echo $this->__('Password'); ?>
									<em>*</em></label>
								<div class="socialpopup-input-box">
									<input type="password" name="password" placeholder="Enter your password" id="password" class="input-text required-entry validate-password" title="<?php echo $this->__('Password'); ?>" />
								</div>
									<div id="formSuccess" style="display: none;">&nbsp;</div>
									<div class="sl_clear"></div>
									<div class="social_login_btn">
									<a href="javascript:void(0);" id="show_password" onclick="show_hide_socialforms('3');"><?php echo $this->__('Forgot Your Password'); ?>?</a>
									<a href="javascript:void(0);" id="register" onclick="show_hide_socialforms('2');"><?php echo $this->__('Create New Account'); ?></a>
										<span id="progress_image_login" style="display: none"> 
											<img src="<?php echo $this->getSkinUrl('sociallogin/images/ajax-loader.gif'); ?>"
													alt="loading please wait" width="16" height="16" /> 
										 </span>
										<button type="button" onclick="socialLoginFrm.submit(this)"
												class="button popup_click_btn" title="<?php echo $this->__('Login') ?>"
												name="send" id="slogin" onSubmit="test();"><span><span> <?php echo $this->__('Login') ?></span></span></button>
									</div>
							</div>
                        </form>
                        <div class="sl_clear"></div>
                        <div id="forget_password_div" style="display: none">
                             <form id="forget_password_form"
                                  action="<?php echo $forgotdirection; ?>"
                                  class="socialpopup_form">
								<div class="modal-header">
									<h4><?php echo $this->__('Forgot Your Password'); ?>?</h4>
								</div>
                                <div class="socialpopup-input-box modal-body">
								<label for="forgotpass" class="required"><?php echo $this->__('Enter your Email Address here to receive a link to change password.'); ?>
                                <em>*</em></label>
								<input type="text" value="" name="forget_password" class="input-text validate-email required-entry"
                                                                          id="forget_password" />
                                    <input type="text" name="extraforgetelement" style="display:none;" placeholder="<?php echo $this->__('Enter Your Email'); ?>" />
                                    <div class="social_login_btn f-right">
                                        <div id="progress_image_forgot" style="display: none;"><img
                                                src="<?php echo $this->getSkinUrl('sociallogin/images/ajax-loader.gif'); ?>"
                                                alt="loading please wait" width="16" height="16" /></div>
                                        <button type="button" id="sforget" onclick="socialforgetFrm.submit(this)"
                                                class="button"><span><span><?php echo $this->__('Submit'); ?></span></span></button>
                                    </div>
                                </div>
                                <div id="forget_password_error"></div>
                            </form>
                        </div>
                        <div class="sl_clear"></div>
                    </div>
                    <?php 
                    /**
                     * Business Fuel - Registration form 
                     */ ?>
                    <div id="register_block" style="display: none;">
                        <div id="register_error" class="popup_error_msg" style="display: none;"></div> 
						<div id="success_msg" class="success" style="display: none;"></div>						
                       <form id="social_frm_register"
                              action="<?php echo $verifyMobile; ?>"
                              class="socialpopup_form">
							<div class="modal-header">
								<h4><?php echo $this->__('Register'); ?></h4>
							</div>
							<div class="modal-body">
                            <label for="first_name" class="required"><?php echo $this->__('First Name'); ?>
                                <em>*</em></label>
                            <div class="socialpopup-input-box"><input type="text" placeholder="Enter your first name" name="firstname"
                                                                      value="" id="first_name" class="input-text required-entry"
                                                                      title="<?php echo $this->__('First Name'); ?>" /></div>
                            <label for="last_name" class="required"><?php echo $this->__('Last Name'); ?>
                                <em>*</em></label>
                            <div class="socialpopup-input-box"><input type="text" placeholder="Enter your last name" name="lastname"
                                                                      value="" id="last_name" class="input-text required-entry"
                                                                      title="<?php echo $this->__('Last Name'); ?>" /></div>
                            <label for="email_register"><?php echo $this->__('Email Address'); ?>
                                </label>
                            <div class="socialpopup-input-box"><input type="text" placeholder="Enter your email address" name="email"
                                                                      value="" id="email_register"
                                                                      class="input-text validate-email"
                                                                      title="<?php echo $this->__('Email Address'); ?>" /></div>
							<!-- Mobile Custom Customer Attribute -->
							<label for="mobile" class="required"><?php echo $this->__('Mobile Number') ?>
                                <em>*</em></label>
                            <div class="socialpopup-input-box"><input type="number" spellcheck="false" placeholder="<?php echo $this->__('Enter your mobile number') ?>" name="mobile"
                                                                      value="" id="mobile"
                                                                      class="input-text validate-number required-entry validate-length maximum-length-10 minimum-length-10 validate-digits"
                                                                      title="<?php echo $this->__('Mobile Number') ?>" /></div>
							<!-- Mobile Custom Customer Attribute -->
                            <label for="password_register" class="required"><?php echo $this->__('Password'); ?>
                                <em>*</em></label>
                            <div class="socialpopup-input-box"><input type="password" placeholder="Enter your Password" 
                                                                      name="password" class="input-text required-entry validate-password"
                                                                      id="password_register" title="<?php echo $this->__('Password'); ?>" />
                            </div>
                            <label for="confirm_password" class="required"><?php echo $this->__('Confirm Password'); ?>
                                <em>*</em></label>
                            <div class="socialpopup-input-box"><input type="password" placeholder="Retype your password" 
                                                                      name="confirmation" value="" id="confirm_password"
                                                                      class="input-text required-entry validate-cpassword"
                                                                      title="<?php echo $this->__('Confirm Password'); ?>" /></div>
                            <?php if ($enableDob != '') { ?> <label for="social_dob"
                                <?php
                                if ($enableDob == 'req') {
                                    echo $reqClass;
                                }
                                ?>><?php echo $this->__('DOB'); ?> <?php
                                           if ($enableDob == 'req') {
                                               echo $emImport;
                                           }
                                           ?></label>
                                <div class="socialpopup-input-box"><input type="text" name="dob"
                                                                          title="<?php echo $this->__('DOB'); ?>" id="social_dob"
                                                                          placeholder="DD/MM/YYYY"
                                                                          class="<?php
                                                                          if ($enableDob == 'req') {
                                                                              echo 'input-text required-entry validate-date-au';
                                                                          }
                                                                          ?>" /></div>                           
                            <?php } if ($enableGender != '') { ?> <label
                                    for="social_gender"
                                    <?php
                                    if ($enableGender == 'req') {
                                        echo $reqClass;
                                    }
                                    ?>><?php echo $this->__('Gender'); ?> <em>*</em></label>
                                <div class="socialpopup-input-box"><select name="gender"
                                                                           id="social_gender">
                                        <option value="1"><?php echo $this->__('Male'); ?></option>
                                        <option value="2"><?php echo $this->__('Female'); ?></option>
                                    </select></div>
                            <?php } if ($enableVat != '') { ?> <label for="taxvat"
                                <?php
                                if ($enableVat == 'req') {
                                    echo $reqClass;
                                }
                                ?>><?php echo $this->__('Tax/VAT number'); ?> <em>*</em></label>
                                <div class="socialpopup-input-box"><input type="text" name="taxvat"
                                                                          title="<?php echo $this->__('Tax/VAT number'); ?>"
                                                                          <?php
                                                                          if ($enableVat == 'req') {
                                                                              echo 'class="input-text required-entry"';
                                                                          }
                                                                          ?>
                                                                          id="taxvat" /></div>
                                <div class="sl_clear"></div>
                            <?php } if ($enableCaptcha) { ?>
                                <div class="sl_captcha"><?php echo $this->getChildHtml('captcha'); ?>
                                </div>
                            <?php } ?>
							</div>
                            <div class="socialpopup-submit-box remove-margin-right">
                                <div class="social_login_btn">
                                    <div id="progress_image_register" style="display: none"><img
                                            src="<?php echo $this->getSkinUrl('sociallogin/images/ajax-loader.gif'); ?>"
                                            alt="loading please wait" width="16" height="16" /></div>
                                    <button type="button" onclick="socialRegisFrm.submit(this)"
                                            title="<?php echo $this->__('Create an Account'); ?>" class="btn btn-primary popup_click_btn"
                                           id="sregister" ><span><span><?php echo $this->__('Create Account'); ?></span></span></button>
                                </div>
                            </div>
                        </form>
                        <?php /** Business Fuel - Registration form */?>
                        <div> 
                            <a href="javascript:void(0);" id="login-pop-up" onclick="show_hide_socialforms('1');"><?php echo $this->__('Login'); ?></a></div>
                        </div>
					<div id="twitter_block" style="display: none;">
                        <?php /** Twitter form  */ ?>
                        <form id="social_tiw_login"
                              action="<?php echo $twitterRedirection; ?>"
                              class="socialpopup_form">
                            <h4><?php echo $this->__('Please Enter your twitter email'); ?></h4>
                            <label for="tw_email" class="required"><?php echo $this->__('Enter Your Email'); ?>
                                <em>*</em></label>
                            <div class="socialpopup-input-box"><input type="text" id="tw_email"
                                                                      name="email_value" value=""
                                                                      class="input-text validate-email required-entry" onkeydown="if (event.keyCode == 13) { socialTwitFrm.submit(this); return false; }" />
                                <div id="twitter_error" class="popup_error_msg"></div>
                                <div class="social_login_btn">
                                    <div id="progress_image_twitter" style="display: none"><img
                                            src="<?php echo $this->getSkinUrl('sociallogin/images/ajax-loader.gif'); ?>"
                                            alt="loading please wait" width="16" height="16" /></div>
                                    <button type="button" onclick="socialTwitFrm.submit(this)"
                                            class="button twitter_popup_btn"><span><span><?php echo $this->__('Submit'); ?></span></span></button>
                                </div>
                            </div>
                        </form>
                        <div class="new_account_create"><?php echo $this->__("Already have an account?"); ?> 
                            <a href="javascript:void(0);" onclick="show_hide_socialforms('1');"><?php echo $this->__('Login!'); ?></a></div>
                    </div>
                </div>

				
            <div class="sl_clear"></div>
        </div>
        <div class="sl_clear"></div>
    </div>
    </div>
    <?php  ?>
    <script type="text/javascript">
         //<![CDATA[
         //<![CDATA[
         var socialLoginFrm = new VarienForm('form_login', true);
         socialLoginFrm.submit = function() {
             if (this.validator.validate()) {
                 var form = this.form;
                 doSociallogin(form.id, form.action, 'formSuccess', 'progress_image_login');
             }
         }.bind(socialLoginFrm);
         var socialRegisFrm = new VarienForm('social_frm_register', true);
         socialRegisFrm.submit = function() {
             if (this.validator.validate()) {
				 jQuery('#sregister').attr('disabled', true);
                 var form = this.form;
                 doSociallogin(form.id, form.action, 'register_error', 'progress_image_register');
             }
         }.bind(socialRegisFrm);
         var socialforgetFrm = new VarienForm('forget_password_form', true);
         socialforgetFrm.submit = function() {
             if (this.validator.validate()) {
                 var form = this.form;
                 doSociallogin(form.id, form.action, 'forget_password_error', 'progress_image_forgot');
             }
         }.bind(socialforgetFrm);
         var socialTwitFrm = new VarienForm('social_tiw_login', true);
         socialTwitFrm.submit = function() {
             if (this.validator.validate()) {
                 var form = this.form;
                 doSociallogin(form.id, form.action, 'twitter_error', 'progress_image_twitter');
             }
         }.bind(socialTwitFrm);
         //]]>
    </script>
    <div id="fb-root"></div>
    <?php
    /**
     * Checking if the base URL is https or not
     *
     * @return string
     */
    $currentUrl = Mage::helper('core/url')->getCurrentUrl();
    $secureUrl = strstr($currentUrl, "https");   
    if ($secureUrl == true) {
        $siteBaseUrl = Mage::getUrl('sociallogin/index/fblogin', array('_secure' => true));
    } else {
        $siteBaseUrl = Mage::getUrl('sociallogin/index/fblogin');
    }
    ?>
	<?php if($fbStatus){ ?>
    <script type="text/javascript">   
		function fblogin() {
            FB.login(function(response) {
				if (response.authResponse) {
                FB.getLoginStatus(function(response) {
                    if (response.status === 'connected') {
                        document.getElementById('progress_image_facebooklogin').style.display = "block";
                        login();
                    }
                });
				} else {
					console.log('User cancelled login or did not fully authorize.');
				}
            }, {scope: 'email,public_profile',return_scopes: true});
            return false;
        }
        window.fbAsyncInit = function() {
            FB.init({appId: '<?php echo $facebookappId; ?>', status: true, cookie: true, xfbml: true});
        };
        (function() {
            var e = document.createElement('script');
            e.type = 'text/javascript';
            e.src = document.location.protocol +
                    '//connect.facebook.net/en_US/all.js';
            e.async = true;
            document.getElementById('fb-root').appendChild(e);
        }());
        function login() {
       	 FB.api('/me', {fields:'email,first_name,last_name,name'}, function(response) {
            	if(response.email != 'undefined') {
                 window.location.href = '<?php echo $siteBaseUrl; ?>?fb=1&email='+response.email+'&fname='+response.first_name+'&lname='+response.last_name;
            	} });
       }	
	   </script>
		<?php } ?>
	   <script type="text/javascript"> 
        /* Script for Enter Key */
        $('social_popup_main').observe('keypress', socialsignupkeypressHandler);
        function socialsignupkeypressHandler(event) {
            var key = event.which || event.keyCode;
            switch (key) {
                default:
                    break;
                case Event.KEY_RETURN:
                    if ($('login_block').visible() && !$('forget_password_div').visible())
                    {
                        $('slogin').click();
                    }
                    if ($('register_block').visible())
                    {
                        $('sregister').click();
                    }
                    if ($('forget_password_div').visible())
                    {
                        $('sforget').click();
                    }
                    break;
            }
        }
				
function mobileVerification(){
	jQuery('#progress_image_mbv').show();
	jQuery('#mobile_verification_btn').attr('disabled', true);
	var base_url = "<?php echo $createRedirection ?>";
	jQuery.ajax({
		url:base_url,
		data:jQuery('#mobile_verification').serialize(),
		type:'post',
		crossDomain: true,
		dataType:'json',
		success:function(data){
			if(data.success == 1) {
				jQuery('#resend_otp').attr('disabled', true);
				jQuery('#mobile_verification_btn').attr('disabled', true);
				jQuery('#success_msg').html(data.message);
				jQuery('#success_msg').css('color','#3d6611');
				jQuery('#success_msg').css('border','1px solid #a6b595');
				setTimeout(function(){ // wait for 5 secs(2)
					   location.reload();
				  }, 2000); 
			}else{
				jQuery('#mobile_verification_btn').attr('disabled', false);
				jQuery('#success_msg').html(data.message);
				jQuery('#success_msg').css('color','red');
				jQuery('#success_msg').css('border','1px solid #eca1a1');
			}
			jQuery('#progress_image_mbv').hide(); 
		}
	});
}

function resendOtp(){
	jQuery('#progress_image_mbv').show();
	jQuery('#resend_otp').attr('disabled', true);
	var base_url = "<?php echo $resendOtp ?>";
	jQuery.ajax({
		url:base_url,
		data:jQuery('#mobile_verification').serialize(),
		type:'post',
		crossDomain: true,
		dataType:'json',
		success:function(data){
			if(data.success == 1){
				jQuery('#success_msg').html(data.message);
				jQuery('#success_msg').css('color','#3d6611');
				jQuery('#success_msg').css('border','1px solid #a6b595');
			} else {
				jQuery('#success_msg').html(data.message);
				jQuery('#resend_otp').attr('disabled', false);
				jQuery('#success_msg').css('color','red');
				jQuery('#success_msg').css('border','1px solid #eca1a1');
			}
			jQuery('#progress_image_mbv').hide(); 
		}
	});
}
     </script>
	 
<?php } ?>