<?php $posts = $this->getPosts(); ?>
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?> 
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?> 
</div>

<?php echo $this->getChildHtml('smartwave_blog_comments_toolbar'); ?>
<div class="posts-wrap">
<?php foreach ($posts as $post): ?>
    <div class="postWrapper">
        <div class="postBanner hide">
        </div>
        <?php
            $orig_data = $post->getData('created_time');
            $oldLocale = setlocale(LC_COLLATE, "0");
            setlocale(LC_ALL, Mage::app()->getLocale()->getLocaleCode().'.UTF-8');
            $post_day = strftime("%d", strtotime($orig_data) + Mage::getSingleton('core/date')->getGmtOffset());
            $post_month = strftime("%b", strtotime($orig_data) + Mage::getSingleton('core/date')->getGmtOffset());
            setlocale(LC_ALL, $oldLocale);
        ?>
        <div class="post-date">
            <span class="day"><?php echo $post_day; ?></span>
            <span class="month"><?php echo $post_month; ?></span>
        </div>
        <div class="postTitle">
            <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
        </div>
        <div class="postContent"><?php echo $post->getPostContent(); ?></div>

        <div class="postDetails">
            <span><i class="icon-calendar"></i><?php echo $post->getCreatedTime(); ?></span>
            <span><i class="icon-user"></i><?php echo $this->__("By"); ?> <?php echo $post->getUser(); ?></span>
            <span><i class="icon-tag"></i><?php echo $this->getTagsHtml($post) ?></span>
            <?php if ($this->getCommentsEnabled()): ?>
                <span><i class="icon-chat"></i><a href="<?php echo $post->getAddress(); ?>#commentBox" ><?php echo $post->getCommentCount(); ?> Comments</a></span>
            <?php endif; ?>
            <?php $postCats = $post->getCats(); ?>
            <?php if (!empty($postCats)): ?>
                <span><i class="icon-folder-open"></i>
                <?php foreach ($postCats as $data): ?>
                    <a href="<?php echo $data['url']; ?>"><?php echo $data['title']; ?></a><span class="last">,</span>
                <?php endforeach; ?>
                </span>
            <?php endif; ?>
        </div>
        <?php echo $this->getBookmarkHtml($post) ?>
    </div>
<?php endforeach; ?>
</div>
<?php echo $this->getChildHtml('smartwave_blog_comments_toolbar'); ?>
