<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <div class="container" style="margin-top:40px;">
            <div clas="row">
                <div class="col-md-4 altius-prod-detail-image debug">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'wysiwyg/crawlerdrill.png'; ?>"/>
                </div>
                <div class="col-md-8 altius-prod-detail-rightcol debug">
                    <h2>ALTIUS PNEUMATIC CRAWLER DRILL CDR 4</h2>
                    <h3>model :  ebr CDR4</h3>
                    <button type="button" class="btn btn-success altius-price">Rs. 15,50,000</button><span class="taxPara">+ Sales Tax & Transportation will be extra</span>
                    <ul class="altius-specs">
                        <li>Economic</li>
						<li>High Rigidity</li>
						<li>High Drilling Rate</li>
						<li>Widest Choice of Down hole drill or Top Hammer</li>
						<li>Low Weight & Good Balance</li>
                    </ul>
                    <button type="button" class="btn btn-warning btn-weighted" data-toggle="modal" data-target="#myModal">Add to Enquiry</button>
                </div>
            </div>
            <div clas="row">
                <div class="col-md-12 altius-specs-detail">
                    <h3>Detailed Specifications</h3>
                    <table class="table table-striped table-bordered" id="altius-specs-detailed">
                        <thead>
                            <tr>
                                <th>Specifications</th>
                                <th>Unit</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Hole range</td>
                                <td>102mm~115mm</td>
                            </tr>
                            <tr>
                                <td>Hole Depth</td>
                                <td>50feet</td>
                            </tr>
                            <tr>
                                <td>Compressor</td>
                                <td>450cfm/150psi</td>
                            </tr>
                            <tr>
                                <td>Pneumatic Drifter Drilling</td>
                                <td>48mm~76mm</td>
                            </tr>
                            <tr>
                                <td>Mounting</td>
                                <td>Crawler</td>
                            </tr>
                            <tr>
                                <td>Speed</td>
                                <td>3.5km/hr</td>
                            </tr>
                            <tr>
                                <td>Rod length</td>
                                <td>3 mtr</td>
                            </tr>
							 <tr>
                                <td>Feed</td>
                                <td>Chain feed driven by air motor & gearbox</td>
                            </tr>
							<tr>
                                <td>Boom Lift above centre Line</td>
                                <td>45<sup>o</sup>up,30<sup>o</sup>down</td>
                            </tr>
							<tr>
                                <td>Boom Swing</td>
                                <td>45<sup>o</sup>right,45<sup>o</sup>left</td>
                            </tr>
							<tr>
                                <td>Dril Guide Swing (Horizontal)</td>
                                <td>45<sup>o</sup>right,45<sup>o</sup>left</td>
                            </tr>
							<tr>
                                <td>Dril Guide Tilt</td>
                                <td>75<sup>o</sup></td>
                            </tr>
							<tr>
                                <td>Overall Length</td>
                                <td>5,100mm</td>
                            </tr>
							<tr>
                                <td>Overall Width</td>
                                <td>2000mm</td>
                            </tr>
							<tr>
                                <td>Height Tramming</td>
                                <td>1780</td>
                            </tr>
							<tr>
                                <td>Ground Clearance</td>
                                <td>254mm</td>
                            </tr>
							<tr>
                                <td>Weight</td>
                                <td>2680kg</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        
        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close otpCloseBtn" data-dismiss="modal" aria-label="Close" onclick="livescroll()"><span aria-hidden="true">X</span></button>
                <h4 class="modal-title" id="myModalLabel">Enquiry</h4>
              </div>
            <form action="<?php echo $this->getUrl('sociallogin/index/altiusform'); ?>" method="post" id="altius-form-validate">
              <div class="modal-body">
                    <div id="tab-1" class="tab-content current">
                        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
                        <input type="hidden" value="<?php echo $this->helper('core/url')->getCurrentUrl() ?>" name="page_url"/>
                            <div class="form-group">
                                <label for="exampleInputName">Name</label>
                                <input type="text" class="form-control required-entry" name="altius_name" id="altius-name" placeholder="Name">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPhonenumber">Contact number</label>
                                <input type="text" class="form-control validate-number required-entry input-box validate-length maximum-length-10 minimum-length-10 validate-digits" name="phonenumber" id="altius-phonenumber" placeholder="Phone number">
                            </div>
							<div class="form-group">
								<label for="exampleInputlocationRequirement">Location</label>
								<textarea class="form-control required-entry" rows="3" id="altius-locationrequirement" name="location_requiement" placeholder="Location of the requirement"></textarea>
							</div>
                    </div>                    
				</div>
              <div class="modal-footer">
                <button type="submit" class="btn btn-default right submit-btn altius-btn">Submit</button>
              </div>
            </form>
            </div>
          </div>
        </div>
<script type="text/javascript">
//<![CDATA[
	var dataForm = new VarienForm('altius-form-validate', true);
	Validation.add('validate-value-greater-than-one', 'Please enter days greater than 1.', function(v) {
		return Validation.get('IsEmpty').test(v) || (v >= 1);
	});
//]]>
</script>
<script type="text/javascript">
//Disable submit button
	var formAlreadySubmitted = false;
	jQuery('#altius-form-validate').submit(function(e){
	   if(dataForm.validator.validate()){
		  if(formAlreadySubmitted){
			 e.preventDefault();
				return false;
			 }
			 var submitChildren = jQuery(this).find('button[type=submit]');
			 submitChildren.attr('disabled', 'disabled');
			 submitChildren.addClass('disabled');
			 formAlreadySubmitted = true;
		}
	});
</script>