<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
        <div class="container" style="margin-top:40px;">
            <div clas="row">
                <div class="col-md-4 altius-prod-detail-image debug">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'wysiwyg/ebr70ds_1.png'; ?>"/>
                </div>
                <div class="col-md-8 altius-prod-detail-rightcol debug">
                    <h2>altius hydraulic rock breaker</h2>
                    <h3>model :  ebr 70ds</h3>
                    <span class="btn btn-success altius-price">Rs. 6,00,000</span><span class="taxPara">+ Sales Tax & Transportation will be extra</span>
                    <ul class="altius-specs">
                        <li>High Efficient Design.</li>
                        <li>More Power and Impact Energy than Competitors.</li>
                        <li>Warranty of 1000 Hrs. or six months whichever is earlier.</li>
                        <li>Wide Application Range.</li>
                    </ul>
                    <button type="button" class="btn btn-warning btn-weighted" data-toggle="modal" data-target="#myModal" onclick="killscroll()">Add to Enquiry</button>
                </div>
            </div>
            <div clas="row">
                <div class="col-md-12 altius-specs-detail">
                    <h3>Detailed Specifications</h3>
                    <table class="table table-striped table-bordered" id="altius-specs-detailed">
                        <thead>
                            <tr>
                                <th>Specifications</th>
                                <th>Unit</th>
                                <th>Value</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Operating Weight</td>
                                <td>Ton</td>
                                <td>450</td>
                            </tr>
                            <tr>
                                <td>Operating Pressure</td>
                                <td>kg/cm<sup>2</sup></td>
                                <td>120~150</td>
                            </tr>
                            <tr>
                                <td>Required Oil Flow</td>
                                <td>Ipm</td>
                                <td>50~90</td>
                            </tr>
                            <tr>
                                <td>Blow Rate</td>
                                <td>bpm</td>
                                <td>400~800</td>
                            </tr>
                            <tr>
                                <td>Tool Diameter</td>
                                <td>mm</td>
                                <td>75</td>
                            </tr>
                            <tr>
                                <td>Relief Valve Pressure</td>
                                <td>kg/cm<sup>2</sup></td>
                                <td>170</td>
                            </tr>
                            <tr>
                                <td>Suitable Carrier</td>
                                <td>Ton</td>
                                <td>6~9</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        
        <!-- Modal -->
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close otpCloseBtn" data-dismiss="modal" aria-label="Close" onclick="livescroll()"><span aria-hidden="true">X</span></button>
                <h4 class="modal-title" id="myModalLabel">Enquiry</h4>
              </div>
            <form action="<?php echo $this->getUrl('sociallogin/index/altiusform'); ?>" method="post" id="altius-form-validate">
              <div class="modal-body">
                    <div id="tab-1" class="tab-content current">
                        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
                        <input type="hidden" value="<?php echo $this->helper('core/url')->getCurrentUrl() ?>" name="page_url"/>
                            <div class="form-group">
                                <label for="exampleInputName">Name</label>
                                <input type="text" class="form-control required-entry" name="altius_name" id="altius-name" placeholder="Name">
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPhonenumber">Contact number</label>
                                <input type="text" class="form-control validate-number required-entry input-box validate-length maximum-length-10 minimum-length-10 validate-digits" name="phonenumber" id="altius-phonenumber" placeholder="Phone number">
                            </div>
							<div class="form-group">
								<label for="exampleInputlocationRequirement">Location</label>
								<textarea class="form-control required-entry" rows="3" id="altius-locationrequirement" name="location_requiement" placeholder="Location of the requirement"></textarea>
							</div>
                    </div>                    
				</div>
              <div class="modal-footer">
                <button type="submit" class="btn btn-default right submit-btn altius-btn">Submit</button>
              </div>
            </form>
            </div>
          </div>
        </div>
<script type="text/javascript">
//<![CDATA[
	var dataForm = new VarienForm('altius-form-validate', true);
	Validation.add('validate-value-greater-than-one', 'Please enter days greater than 1.', function(v) {
		return Validation.get('IsEmpty').test(v) || (v >= 1);
	});
//]]>    
</script>
<script type="text/javascript">
//Disable submit button
	var formAlreadySubmitted = false;
	jQuery('#altius-form-validate').submit(function(e){
	   if(dataForm.validator.validate()){
		  if(formAlreadySubmitted){
			 e.preventDefault();
				return false;
			 }
			 var submitChildren = jQuery(this).find('button[type=submit]');
			 submitChildren.attr('disabled', 'disabled');
			 submitChildren.addClass('disabled');
			 formAlreadySubmitted = true;
		}
	});
</script>